apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app
  name: springboot-app
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: 092369361076.dkr.ecr.us-east-1.amazonaws.com/test-ecr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              name: http
              protocol: TCP

# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: springboot-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app
